/*
 * ECU_INIT.c
 *
 *  Created on: Oct 2, 2024
 *      Author: Mohamed Elahmady
 */
#include "ECU_INIT.h"

CHR_LCD_4BIT_T lcd1 = {
	.RS_PIN.PORT = PORTC_IND,
	.RS_PIN.PIN = GPIO_PIN0,
	.RS_PIN.DIRECTION = GPIO_OUTPUT,
	.RS_PIN.LOGIC = GPIO_LOW,

	.EN_PIN.PORT = PORTC_IND,
	.EN_PIN.PIN = GPIO_PIN1,
	.EN_PIN.DIRECTION = GPIO_OUTPUT,
	.EN_PIN.LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[0].PORT = PORTC_IND,
	.LCD_DATA_PINS[0].PIN = GPIO_PIN2,
	.LCD_DATA_PINS[0].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[0].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[1].PORT = PORTC_IND,
	.LCD_DATA_PINS[1].PIN = GPIO_PIN3,
	.LCD_DATA_PINS[1].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[1].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[2].PORT = PORTC_IND,
	.LCD_DATA_PINS[2].PIN = GPIO_PIN4,
	.LCD_DATA_PINS[2].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[2].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[3].PORT = PORTC_IND,
	.LCD_DATA_PINS[3].PIN = GPIO_PIN5,
	.LCD_DATA_PINS[3].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[3].LOGIC = GPIO_LOW,
};

CHR_LCD_8BIT_T lcd2 = {
	.RS_PIN.PORT = PORTC_IND,
	.RS_PIN.PIN = GPIO_PIN6,
	.RS_PIN.DIRECTION = GPIO_OUTPUT,
	.RS_PIN.LOGIC = GPIO_LOW,

	.EN_PIN.PORT = PORTC_IND,
	.EN_PIN.PIN = GPIO_PIN7,
	.EN_PIN.DIRECTION = GPIO_OUTPUT,
	.EN_PIN.LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[0].PORT = PORTD_IND,
	.LCD_DATA_PINS[0].PIN = GPIO_PIN0,
	.LCD_DATA_PINS[0].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[0].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[1].PORT = PORTD_IND,
	.LCD_DATA_PINS[1].PIN = GPIO_PIN1,
	.LCD_DATA_PINS[1].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[1].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[2].PORT = PORTD_IND,
	.LCD_DATA_PINS[2].PIN = GPIO_PIN2,
	.LCD_DATA_PINS[2].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[2].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[3].PORT = PORTD_IND,
	.LCD_DATA_PINS[3].PIN = GPIO_PIN3,
	.LCD_DATA_PINS[3].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[3].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[4].PORT = PORTD_IND,
	.LCD_DATA_PINS[4].PIN = GPIO_PIN4,
	.LCD_DATA_PINS[4].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[4].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[5].PORT = PORTD_IND,
	.LCD_DATA_PINS[5].PIN = GPIO_PIN5,
	.LCD_DATA_PINS[5].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[5].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[6].PORT = PORTD_IND,
	.LCD_DATA_PINS[6].PIN = GPIO_PIN6,
	.LCD_DATA_PINS[6].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[6].LOGIC = GPIO_LOW,

	.LCD_DATA_PINS[7].PORT = PORTD_IND,
	.LCD_DATA_PINS[7].PIN = GPIO_PIN7,
	.LCD_DATA_PINS[7].DIRECTION = GPIO_OUTPUT,
	.LCD_DATA_PINS[7].LOGIC = GPIO_LOW,
};

//LED_T led1 = {
//	.LED_Pin.PORT = PORTC_IND,
//	.LED_Pin.PIN = GPIO_PIN0,
//	.LED_Pin.DIRECTION = GPIO_OUTPUT,
//	.LED_Pin.LOGIC = GPIO_LOW
//};
void ECU_INITIALIZE(void){
	Std_ReturnType Ret = E_NOT_OK;
	Ret = CHR_LCD_4BIT_INITIALIZE(&lcd1);
	Ret = CHR_LCD_8BIT_INITIALIZE(&lcd2);
//	Ret = LED_INITIALIZE(&led1);
}
