/*
 * ECU_INIT.c
 *
 *  Created on: Oct 2, 2024
 *      Author: Mohamed Elahmady
 */
#include "ECU_INIT.h"

KEYPAD_T keypad1 = {
		.KEYPAD_ROWS_PINS[0].PORT = PORTC_IND,
		.KEYPAD_ROWS_PINS[0].PIN = GPIO_PIN0,
		.KEYPAD_ROWS_PINS[0].DIRECTION = GPIO_OUTPUT,
		.KEYPAD_ROWS_PINS[0].LOGIC = GPIO_LOW,

		.KEYPAD_ROWS_PINS[1].PORT = PORTC_IND,
		.KEYPAD_ROWS_PINS[1].PIN = GPIO_PIN1,
		.KEYPAD_ROWS_PINS[1].DIRECTION = GPIO_OUTPUT,
		.KEYPAD_ROWS_PINS[1].LOGIC = GPIO_LOW,

		.KEYPAD_ROWS_PINS[2].PORT = PORTC_IND,
		.KEYPAD_ROWS_PINS[2].PIN = GPIO_PIN2,
		.KEYPAD_ROWS_PINS[2].DIRECTION = GPIO_OUTPUT,
		.KEYPAD_ROWS_PINS[2].LOGIC = GPIO_LOW,

		.KEYPAD_ROWS_PINS[3].PORT = PORTC_IND,
		.KEYPAD_ROWS_PINS[3].PIN = GPIO_PIN3,
		.KEYPAD_ROWS_PINS[3].DIRECTION = GPIO_OUTPUT,
		.KEYPAD_ROWS_PINS[3].LOGIC = GPIO_LOW,

		.KEYPAD_COLUMNS_PINS[0].PORT = PORTC_IND,
		.KEYPAD_COLUMNS_PINS[0].PIN = GPIO_PIN4,
		.KEYPAD_COLUMNS_PINS[0].DIRECTION = GPIO_INPUT,

		.KEYPAD_COLUMNS_PINS[1].PORT = PORTC_IND,
		.KEYPAD_COLUMNS_PINS[1].PIN = GPIO_PIN5,
		.KEYPAD_COLUMNS_PINS[1].DIRECTION = GPIO_INPUT,

		.KEYPAD_COLUMNS_PINS[2].PORT = PORTC_IND,
		.KEYPAD_COLUMNS_PINS[2].PIN = GPIO_PIN6,
		.KEYPAD_COLUMNS_PINS[2].DIRECTION = GPIO_INPUT,

		.KEYPAD_COLUMNS_PINS[3].PORT = PORTC_IND,
		.KEYPAD_COLUMNS_PINS[3].PIN = GPIO_PIN7,
		.KEYPAD_COLUMNS_PINS[3].DIRECTION = GPIO_INPUT,

		.KEYPAD_CON = KEYPAD_ACTIVE_HIGH
};

LED_T led1 = {
		.LED_Pin.PORT = PORTD_IND,
		.LED_Pin.PIN = GPIO_PIN0,
		.LED_Pin.DIRECTION = GPIO_OUTPUT,
		.LED_Pin.LOGIC = GPIO_LOW
};

void ECU_INITIALIZE(void){
	Std_ReturnType Ret = E_NOT_OK;
	Ret = KEYPAD_INITIALIZE(&(keypad1));
	Ret = LED_INITIALIZE(&(led1));
}
